apiVersion: v1
kind: Service
metadata:
  name: log360-web-service
  namespace: log360-lab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  selector:
    app: log360-web-portal
---
apiVersion: v1
kind: Service
metadata:
  name: log360-syslog-service
  namespace: log360-lab
spec:
  type: ClusterIP
  ports:
  - port: 514
    targetPort: 514
    protocol: UDP
    name: syslog-udp
  selector:
    app: log360-web-portal
